### ISSUE TITLE
on page refresh, showing undefined for all counter variables

### ISSUE THREAD

**Issue by bnbabu55** [rallisf1/svelte-counter#2]
First of all, thanks for this tool. I just installed it in my project, it works fine.

My only gripe is that when the page loads or refreshes, undefined is displayed for all counter variables, if this can be shown as 0 for all variables, it should be fine. 

For now, I have put in the check to see if the value is set then show variable or show 0 like below, now I am seeing 0 on page refresh.

`{counterResult.projects ? counterResult.projects : 0}`

Thanks

**Comment by rallisf1** [comment]
let me know if the fix works for you

**Comment by bnbabu55** [comment]
Thanks John, this fix is working fine now. I am closing this issue.
